Updates 2020-07-07
divio/ac-base pull request #15
Opened 2020-07-07 10:24 UTC by koniiiik

2020-07-07 11:42 UTC, GaretJax requested changes

2020-07-07 11:42 UTC, GaretJax commented on py3.6-alpine3.12/Dockerfile
> +RUN echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories
If we don't use any @edge packages, I think we can remove these three lines.

2020-07-07 11:42 UTC, GaretJax commented on py3.6-alpine3.12/Dockerfile
> +RUN pip install pip-reqs==0.8.0
pip-reqs 0.8.5 is available; would be good to upgrade wherever possible

2020-07-08 08:23 UTC, GaretJax approved these changes

2020-07-08 14:45 UTC, merged

2020-07-13 06:17 UTC, vinitkumar commented
Is this also released on docker-hub?